use std::any::TypeId;
use std::collections::HashMap;

use crate::bundle::Bundle;
use crate::component::{ComponentId, ComponentRegistry};
use crate::storage::archetype::{ArchetypeId, Archetypes};

/// Cached column layout for a Table type. Resolved once on first use.
pub struct TableDescriptor {
    pub archetype_id: ArchetypeId,
    /// Maps field index (0, 1, 2...) to archetype column index.
    /// Field order matches struct declaration order; column order is
    /// sorted by ComponentId (archetype canonical order).
    pub col_indices: Vec<usize>,
    /// Item sizes for each field in field declaration order.
    pub item_sizes: Vec<usize>,
}

/// A named struct that serves as both data container and schema declaration.
/// Generated by `#[derive(Table)]`.
///
/// # Safety
/// Implementors must ensure that `register` returns component IDs matching
/// the actual field types in declaration order, and `FIELD_COUNT` matches
/// the actual number of fields.
pub unsafe trait Table: Bundle + Sized {
    const FIELD_COUNT: usize;

    /// Register all field components. Returns ComponentIds in field declaration order.
    fn register(registry: &mut ComponentRegistry) -> Vec<ComponentId>;
}

/// Cache of resolved TableDescriptors, keyed by TypeId.
pub(crate) struct TableCache {
    descriptors: HashMap<TypeId, TableDescriptor>,
}

impl TableCache {
    pub fn new() -> Self {
        Self {
            descriptors: HashMap::new(),
        }
    }

    /// Get or create the descriptor for a Table type.
    pub fn get_or_create<T: Table>(
        &mut self,
        components: &mut ComponentRegistry,
        archetypes: &mut Archetypes,
    ) -> &TableDescriptor {
        let type_id = TypeId::of::<T>();
        self.descriptors.entry(type_id).or_insert_with(|| {
            // Register components in field order
            let field_ids = T::register(components);

            // Archetype uses sorted component IDs
            let mut sorted_ids = field_ids.clone();
            sorted_ids.sort_unstable();
            sorted_ids.dedup();
            assert_eq!(
                sorted_ids.len(),
                T::FIELD_COUNT,
                "duplicate component types in table"
            );

            let arch_id = archetypes.get_or_create(&sorted_ids, components);
            let archetype = &archetypes.archetypes[arch_id.0];

            // Map field index -> archetype column index
            let col_indices: Vec<usize> = field_ids
                .iter()
                .map(|comp_id| archetype.component_index[comp_id])
                .collect();

            let item_sizes: Vec<usize> = field_ids
                .iter()
                .map(|&comp_id| components.info(comp_id).layout.size())
                .collect();

            TableDescriptor {
                archetype_id: arch_id,
                col_indices,
                item_sizes,
            }
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::component::ComponentRegistry;
    use crate::storage::archetype::Archetypes;

    // Manual Table impl for testing (before derive macro works)
    #[derive(Clone, Copy, Debug, PartialEq)]
    struct Pos {
        x: f32,
        y: f32,
    }
    #[derive(Clone, Copy, Debug, PartialEq)]
    struct Vel {
        dx: f32,
        dy: f32,
    }

    struct PosVel {
        pos: Pos,
        vel: Vel,
    }

    unsafe impl Bundle for PosVel {
        fn component_ids(registry: &mut ComponentRegistry) -> Vec<ComponentId> {
            let mut ids = vec![registry.register::<Pos>(), registry.register::<Vel>()];
            ids.sort_unstable();
            ids.dedup();
            assert_eq!(ids.len(), 2);
            ids
        }

        unsafe fn put(
            self,
            registry: &ComponentRegistry,
            func: &mut dyn FnMut(ComponentId, *const u8, std::alloc::Layout),
        ) {
            let pos = std::mem::ManuallyDrop::new(self.pos);
            func(
                registry.id::<Pos>().unwrap(),
                &*pos as *const Pos as *const u8,
                std::alloc::Layout::new::<Pos>(),
            );
            let vel = std::mem::ManuallyDrop::new(self.vel);
            func(
                registry.id::<Vel>().unwrap(),
                &*vel as *const Vel as *const u8,
                std::alloc::Layout::new::<Vel>(),
            );
        }
    }

    unsafe impl Table for PosVel {
        const FIELD_COUNT: usize = 2;

        fn register(registry: &mut ComponentRegistry) -> Vec<ComponentId> {
            vec![registry.register::<Pos>(), registry.register::<Vel>()]
        }
    }

    #[test]
    fn descriptor_resolves_correctly() {
        let mut components = ComponentRegistry::new();
        let mut archetypes = Archetypes::new();
        let mut cache = TableCache::new();

        let desc = cache.get_or_create::<PosVel>(&mut components, &mut archetypes);
        assert_eq!(desc.col_indices.len(), 2);
        assert_eq!(desc.item_sizes.len(), 2);
    }

    #[test]
    fn descriptor_is_cached() {
        let mut components = ComponentRegistry::new();
        let mut archetypes = Archetypes::new();
        let mut cache = TableCache::new();

        let id1 = cache
            .get_or_create::<PosVel>(&mut components, &mut archetypes)
            .archetype_id;
        let id2 = cache
            .get_or_create::<PosVel>(&mut components, &mut archetypes)
            .archetype_id;
        assert_eq!(id1, id2);
    }

    #[test]
    fn col_indices_map_field_to_column() {
        let mut components = ComponentRegistry::new();
        let mut archetypes = Archetypes::new();
        let mut cache = TableCache::new();

        let desc = cache.get_or_create::<PosVel>(&mut components, &mut archetypes);
        // Both fields should have valid column indices
        let archetype = &archetypes.archetypes[desc.archetype_id.0];
        for &col_idx in &desc.col_indices {
            assert!(col_idx < archetype.columns.len());
        }
    }
}
